#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Set the apc.shm_size to 160 megabytes if it has not yet been sent.
if [[ -z $OPENSHIFT_PHP_APC_SHM_SIZE ]]; then
  echo "160M" > ~/.env/user_vars/OPENSHIFT_PHP_APC_SHM_SIZE
  gear stop --cart php
  gear start --cart php
fi
